### ISSUE TITLE
How does one select a device?

### ISSUE THREAD

**Issue by mscheper** [mckset/KD100#10] opened 2024-07-22 18:43 UTC
Even though this is written for different hardware, I hope this project may still help me use my Huion Keydial mini K20 with Linux Mint.

I've gotten it to compile (I had to install `g++` in Apt to get `make` to work), but when I run KD100, I see this:

```
Bus 008 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 007 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 002: ID 174f:11a8 Syntek Integrated Camera
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 06cb:00f9 Synaptics, Inc. 
Bus 001 Device 004: ID 10ab:9309 USI Co., Ltd 
Bus 001 Device 002: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 001 Device 005: ID 256c:0069 HUION Huion Keydial_K20
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Select a device to use: 
```

Obviously the second-last device is the one I want, but how do I select it? I've tried typing '256c:0069', '005' and 'Bus 001 Device 005', and I just get the same prompt back.

Thanks.

**Comment by mckset** [comment] 2024-07-22 21:15
The driver should list all the devices that match the VID and PID in the program after listing all the USB devices. It looks like your device isn't being found. Did you change the VID and PID at the top of the program to match the K20? In your case it looks like you would only have the change the PID to 0x0069 and recompile.

**Comment by mscheper** [comment] 2024-07-24 14:31
Thanks for your reply. I've done as you've suggested, and the K20 comes up as an option now, but it doesn't seem to be working. Running your driver _does_ make the out-of-the-box behaviour stop: When I plug the keypad in without running your driver, some of the buttons act like keypresses, and when I run your driver, that no longer happens… but the keypresses defined in default.cfg don't happen, either.

I've tried running your driver with `-d` and `-dry` (separately) and I'm not seeing any extra output, except that it lists the config with `-d`, before I select the keypad. I've tried changing the config file to make it launch programs (by setting `type: 1` and e.g. `function: gnome-calculator`), and that doesn't make those buttons do anything, either. What I'm doing is running `sudo ./KD100` from the KD100 repo directory, after re`make`ing it. I tried running `make` with `sudo` as well, and while it copied default.cfg to $HOME/.config/KD100, it still didn't make a difference.

Do you think it simply won't work with the K20 (even though it apparently has the same button layout and the driver seems to recognise it), or are there other things I can try, before giving up and returning this keypad?

Cheers.

**Comment by mckset** [comment] 2024-07-24 15:21
My guess is that Huion changed the way the K20 sends data compared to the KD100. I've been trying to work on a generic replacement driver and seeing how other companies handle sending USB data, I would think this is the case. If you run KD100 -d -d (using -d twice) it will display the binary data received from the device. Which should look something like this though numbers might be different:

```
DATA: [8, 224, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

The only other device I have to test this with is an XP-Pen shortcut remote but the concept should be the same. By seeing the sent data, you should be able to map the buttons to your device. Line 326 handles converting the data into keycodes for triggering events

```
// Convert data to keycodes
if (data[4] != 0)
	keycode = data[4];
else if (data[5] != 0)
	keycode = data[5] + 128;
else if (data[6] != 0)
	keycode = data[6] + 256;
if (data[1] == 241)
	keycode+=512;
```

I don't know how much programing experience you have but the data is displayed as an array and by pressing a button and counting to the byte that changed, you can change the index of the data variable to match those buttons. So on the KD100, elements 0, 2, and 3 are not used but element 1 tells the driver whether you pushed a regular button or the wheel button, setting the value to 241 if the wheel button was pushed. Elements 4-6 tell the driver that a button was pushed if or the wheel was moved. In the case of the KD100, Huion used element 5 for both wheel directions and buttons and sets element 1 to 241 if the input was from the wheel.  If you want to send me the data for both wheel directions, the wheel button and which bytes change for each button, I can create a K20 branch for your device.

**Comment by mscheper** [comment] 2024-07-24 17:10
That's helpful info, and while I mostly code in higher level languages, I'm pretty sure I still know enough C to make this work… I just don't know anything about coding device drivers.

However, when I run `sudo ./KD100 -d -d` and select the device, still nothing happens when I press the buttons or turn the wheel. I tried a different USB port, too, just in case that made a difference. So perhaps I'm missing something more fundamental. Changing the PID to 0x0069 and recompiling did make the device selectable, but is there anything else I should check? It's quite a new OS installation so I doubt anything's messing up access to the ports, but is there anything I could do to make sure?

**Comment by mckset** [comment] 2024-07-24 20:31
That is strange. I was able to get the XP-Pen device to display the data and even got a Xbox controller to show the data. There might be something else with the device that I just don't expect. The only other thing I could think of it being is if the device is using a different endpoint than the KD100.  If you run:

```
lsusb -v -d 256c:0069 | grep bEndpointAddress
```

It should list all the endpoint your devices uses. The KD100 lists 3 endpoints but only uses 0x81. If you change the 0x81 endpoint on line 304 to match any of the listed endpoints, it might work.

```
err = libusb_interrupt_transfer(handle, 0x81, data, sizeof(data), NULL, 0); // Get data
```

Other than that, I can't think of anything else it could be since I don't have one here to test.

**Comment by Ruaidrhi** [comment] 2024-07-25 02:46
I've been messing around with trying to get this to work as well- I have some info that may or may not be useful. I managed to get it entirely working with the KD20 only by updating the PID to match- no other changes were required, 100% functional. However, oddly, and ironically, it only works if I exit my tablet software first. I got the KD20 as a pack-in with a graphics tablet, and had to install the huion linux drivers for that, somehow they seem to clash with your KD100 driver. 

Maybe other USB devices/drivers can clash with it somehow? If I have the tablet driver active, I can't even start up the driver, I just get a "DEVICE IS ALREADY IN USE" error. I can kind of hack around it by first connecting to the computer via bluetooth and then plugging in the device, then starting the KD100 driver- but then I get the issues mentioned above, no response to any keypresses, no reaction with -d -d. 

I'm an artist, not a programmer, I only know the basics from some hobby coding on the side so I can't help out a ton on the code side, but I have copious amounts of time to try random stuff and share the results here if it will help out. Would love to get this working!

**Comment by mckset** [comment] 2024-07-25 17:05
This might actually help a lot but I'm going to need some clarification. 

1) When you got the driver to work, you said you had to close Huions software first. So, I'm guessing you are saying that my driver on it's own doesn't until you open Huions software and then close it right?

2) Are you trying to use my driver with Bluetooth or a USB device? The driver was designed around the KD100 which did not support Bluetooth and had a USB dongle that the driver relies on. It could also be connected to a PC through a USB cord and it would work the same.

The clashing between my driver and Huions is expected since, as far as I can tell, only one program can control a USB device at one time but it might explain what is going on. I don't use Huion tablets so I can't say for sure that this is happening but my guess is that the software is taking over the USB control for the K20. My program doesn't have a timeout option and just waits until it receives the next input. If you change the 0 in line 304 to 1000 and change the if statement on line 319 to read 

```
if (err < 0 && err != LIBUSB_ERROR_TIMEOUT)
```

It should at a 1 second timeout. If you try to run it and then start the Huion software, my driver should give an error other than a timeout error if the Huion software is taking over the USB control. To which you might be able to tell the Huion software to ignore the K20. Otherwise it might be something else I would have to look into.

**Comment by Ruaidrhi** [comment] 2024-07-25 17:55
It didn't even occur to me because my tablet software was loading on startup, but yes, it looks like i have to first open and close the tablet software before the K20 will work as expected. Just trying it without loading the software first did nothing. 

I'm using it via USB cable. I'm no programmer but looking at the code and seeing "libusb" everywhere made it pretty clear this was expecting USB, I can live with that, hah. 

I spent a bit of time fiddling around- adding the 1000ms timeout would result in the keypad always shutting down after one second unless keys were actively pressed. I did try starting the huion software to see if I could get any useful errors, but it either timed out if I wasn't pushing buttons, or if I was it just... worked? Reverting back to the original code, if I first open the huion software, then close it, then open your driver, _then_ open the huion drivers again, everything just works as expected. 

This is a bit of a dance to have to do each time I want to use it, but at least it works I suppose. Still, if there's anything I can do to provide useful info that might help make this process less clunky let me know. 

Also, just in case they're relevant somehow, I noticed the bit about un-commenting out a line to get more error reporting, so I did that and get two errors that may or may not be relevant. When attempting to load the driver without doing all the shenanigans that make it work first, upon initially loading the driver and before choosing a device the message: 

"libusb: error [usbi_get_context] API misuse! Using non-default context as implicit default."

Pops up. I'm guessing this isn't important since the driver always gets past this part without issue. When selecting a device, the driver successfully starts running, but then immediately spits out 

"libusb: error [submit_bulk_transfer] submiturb failed, errno=16"

and then closes. 

Doing the huion-software open-close-load your driver-open dance doesn't show this error and then everything works, so maybe it's related? I spent some time googling it but it's all a bit above my head I'm afraid.

**Comment by mckset** [comment] 2024-07-25 20:00
The first libusb error is normal and the second one means the device was busy so running it a second time probably would have worked. As for the whole open-close thing, I can't say for sure what is happening with it. I tried installing the Huion tablet software on my PC and I couldn't get it to recognize my device (I don't know if it needs a tablet to work or not). The weird part to me is that you have to load the Huion software first since a USB device should work regardless. The only thing I can think of it being is maybe Huions software loads a module or does a "handshake" with the device and tells it to start sending data. I can't say for sure since I don't have a K20 and their software is proprietary. There are a couple of things you can do to test for that such as USB sniffing/monitoring to see if the Huion driver does communicate with the K20 first and if so, it wouldn't be difficult to do the same with my driver as long as I know the endpoint and what data to send. Somehow I doubt that this is the case but I can't think of another reason the device wouldn't work until you started the software. At least it can work for now even though it's a bit hacky but it's better than nothing I guess. I'm going to consider this as solved for now but I will leave the issue open in case any new information is found.

**Comment by Ruaidrhi** [comment] 2024-07-25 20:54
I think you're on to something with the handshake idea- if I try the open and close thing with the K20 unplugged, then plug it in and start your driver, it doesn't work. The K20 has to be plugged in. I had to look up how to do it, but I messed around with USB sniffing and it does look like when the tablet software is loaded up, they communicate with each other... It's mostly greek to me, but I popped some of the output that looked like long strings of hex into a converter, and starting up the tablet software while monitoring the tablet it sent out a bunch of messages with "Huion Tablet something something" as the data words, and similarly starting up the tablet software while monitoring the keydial it does the same but with "Huion Keydial etc", I forget the exact words but that's not important, hah. 

So to my layman eyes at least, it looks like they're talking since starting the tablet software makes the keydial send/receive a bunch of stuff. Or maybe this means nothing, I dunno, I'm an art guy not a computer guy. 

Anyway, the issue is certainly solved enough for me, but if you're curious I can get you the results of the USB sniffing when turning on the software. It's... a lot, so I won't just dump it here unless you want it.

**Comment by Ruaidrhi** [comment] 2024-07-26 03:04
Okay, I'm a big ole' dummy. I just noticed that the huion tablet driver is also supposed to be the K20 driver, so _of course_ it's trying to communicate with the device. It's trying to be a driver, the huion guys just didn't do whatever magic is necessary to finish the job for linux, so it just sort of connects and blocks your driver without actually doing anything. This explains why I kept getting "DEVICE ALREADY IN USE" errors unless I shut the huion drivers down before starting your driver. 

So the trick is to break this connection before trying to connect to the K20 with your driver. 

I'm 100% certain there must be a more elegant way to do this, but after some searching on how to disconnect USB devices with libusb, I tossed `libusb_reset_device(handle);` right above `libusb_kernel_driver_active(handle, x);` on line 290. The terminal spits out a few hotplug errors, but then it seems to go on to work just fine, without having to do the open-close-open dance. Now I can just load up the huion drivers, load up your drivers, and go.

**Comment by mckset** [comment] 2024-07-26 20:43
I cannot believe I didn't think about that. I would instead move the reset function before line 286 to prevent it from running multiple times in the for loop (which might be the cause of the hotplug errors you get since I didn't get any from my version). I created a new branch called v1.4.3 which contains your suggested change and a couple of added commands to allow you to change the drivers VID and PID after compiling. If you would like to test it and let me know if it works for you, that would be great.

**Comment by Ruaidrhi** [comment] 2024-07-27 01:39
Gave the new version a test- everything seems to be functioning, the command for manually entering the PID worked as expected, driver fired up no problem and no more hotplug errors. I think you got 'er. Thanks! And thanks your hard work on the driver generally. The keydial is a handy little gadget and it would have been a real shame to have to just leave it in the box.

**Comment by mckset** [comment] 2024-07-27 01:46
Glad it worked. I'll try to push the update tomorrow.

**Closed as completed by mckset** 2024-07-27 01:46 UTC

**Comment by mscheper** [comment] 2024-08-07 22:02
@mckset:
> Other than that, I can't think of anything else it could be since I don't have one here to test.

Totally fair. I never did get it to work, but unlike @Ruaidrhi, I'm not trying to use it with a tablet. So I'm going to just try other hardware some time. I really appreciate your time.

**Comment by mscheper** [comment] 2024-08-07 22:04
@mckset:
> Other than that, I can't think of anything else it could be since I don't have one here to test.

Totally fair. I never did get it to work, but unlike @Ruaidrhi, I'm not trying to use it with a tablet. So I'm going to just try other hardware some time. I really appreciate your time.

**Comment by Ruaidrhi** [comment] 2024-08-07 22:15
@mckset

For what it's worth, I just gave it a test without the tablet at all connected to my computer and it worked just fine. It seems to need the huion driver _as well_ as this driver, but it does work- no tablet necessary. If you want to get it working, grabbing any of the freely available huion drivers (mine's the kamvas 19 pro so that's a safe bet) should be all you need to do.

**Comment by jlitowitz-ets** [comment] 2024-11-08 01:05
Hi, I am facing the same with the k20.  When I changed the 0x81 to 0x82, I started getting the DATA lines to print out, for every button except the wheel and wheel button.  If I change it to 0x83, I get the wheel & wheel button data to print out, but not the rest of the keys.

Regardless of whether I use 0x82 or 0x83 I get no inputs in any other applications, even if I remove one or both of the -d flags.

Any thoughts on what I could try next?  xdotool is installed, and I can run it from the command line and get it to, well, do stuff.  My C is *extremely* rusty, so anything more than a basic change like the above might be beyond my reach, but I'm willing to try.

**Comment by jlitowitz** [comment] 2024-11-08 01:07
Hi, I'm facing the same issue with my k20.  When I change the 0x81 to 0x82, I can get the Data arrays to print out for all keys except the wheel and wheel button; if I change it to 0x83, I get the wheel and wheel button, but none of the rest of the keys.  Regardless, I don't seem to get any input passed on to any other programs, even if I remove one or both of the -d flags.

Any thoughts on what I could try next?

**Comment by mckset** [comment] 2024-11-08 01:26
By the sounds of it, the program would have to be altered to account for the K20. Can you send the data array showing which bytes change for the keys and which bytes change for the wheel and wheel button? If nothing is happening, there's a chance Huion changed how the data is sent compared to the K100 and the program would need to be updated to account for this. Since the device uses 2 endpoints, I might be able to figure out a solution but I would need you to verify that it works and I don't own a K20. 

If you want to try and fix it yourself, line 304-308 would probably need to change to be something like this:
```
err = libusb_interrupt_transfer(handle, 0x82, data, sizeof(data), NULL, 10); // Get key data with 10 ms timeout

if (err == LIBUSB_ERROR_TIMEOUT)
    err = libusb_interrupt_transfer(handle, 0x83, data, sizeof(data), NULL, 10); // Get wheel data with 10ms timeout

if (err == LIBUSB_ERROR_TIMEOUT)
    err = 0;

// Potential errors
```

And then you would need to change the index of the data array from lines 327-333 to match the bytes that you saw change with the debug flags enabled. Otherwise I can create a separate branch for it and try to fix it if you send that data.

**Comment by jlitowitz** [comment] 2024-11-08 01:43
I'll do you one better.  I was able to work out the following for the keycodes array.  This, along with changes to the if/else block (more below) seem to make it work for everything except the wheel + wheel button (the 0x82 vs 0x83 thing):

int keycodes[] = {142, 138, 143, 204, 140, 135, 133, 136, 150, 157, 134, 153, 1, 4, 2, 168, 145, 258, 260, 641, 642};

As for the if/else block, I changed these lines to use the updated array indexes.

				// Convert data to keycodes
				if (data[1] != 0)
					keycode = data[1];
				else if (data[2] != 0)
					keycode = data[2] + 128;

Thanks for the guidance on the 0x83 thing - my C is waaay out of date (like, 30 years out of date).  Surprised I was able to get this far.

**Comment by jlitowitz** [comment] 2024-11-08 02:29
Ok, I'm at a loss as to what to do for the wheel & wheel button.  Restarting the app, when I rotate the wheel to the right, data[0] = 17, data[2] contains some value that is usually between 0-15 or so ... it kind of increases as I continue to rotate the wheel, especially at a higher speed, but it's not consistent, and  data[3] is 0 ... I know this may seem irrelevant at the moment, but it becomes more so later on:

```
DATA: [17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
DATA: [17, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
DATA: [17, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
DATA: [17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
DATA: [17, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
DATA: [17, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

Again restarting the app, when I scroll the wheel to the left, data[0] again is 17, data[2] seems to again be in the positive single digits for a bit ... but then goes to 255 and/or a little less.  I mentioned data[3] though - when data[2] goes up to 255, data[3] also goes up to 255, and stays at 255, regardless of the value of data[2] ... until i rotate right again for a bit and loop back around to 0 and positive single digits.

```
DATA: [17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
DATA: [17, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
DATA: [17, 0, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
DATA: [17, 0, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
DATA: [17, 0, 254, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
DATA: [17, 0, 254, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
DATA: [17, 0, 252, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
DATA: [17, 0, 253, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

As for the wheel button ... yeah, this one is really wild.  When I FIRST hit the button, it seems to emit data just like for the last rotating status, as if it's trying to flush a memory buffer or something.  Eventually, it'll settle in on data[0] = 17, data[1] = 3, all other bits 0:

```
DATA: [17, 0, 247, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
DATA: [17, 0, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
DATA: [17, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
DATA: [17, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
DATA: [17, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

I didn't even notice that one record with data[1] = 2 until pasting in here.

**Comment by mckset** [comment] 2024-11-08 02:53
It's hard to tell without having a device of my own. But if the wheel and buttons are sharing indexes 1-3, you may have to create a separate data array just for the wheel unless you can figure out how Huion is able to separate the buttons from the wheel. 

```
unsigned char data[40]; // Stores device button  input
unsigned char wheelData[40]; // Stores device wheel input

int keycode = 0; // Keycode read from the device
err = libusb_interrupt_transfer(handle, 0x82, data, sizeof(data), NULL, 10); // Get key data with 10 ms timeout

if (err == LIBUSB_ERROR_TIMEOUT)
    err = libusb_interrupt_transfer(handle, 0x83, wheelData, sizeof(wheelData), NULL, 10); // Get wheel data with 10ms timeout

if (err == LIBUSB_ERROR_TIMEOUT)
    err = 0;

// Potential errors
```

For the wheel button, I'm wondering if it is set to 2 to let the program know it was clicked and then uses 3 to tell it that the button is being held. That's the only reason I can think of for it starting at 2 but it could be something else. 

For the wheel itself, it's weird to me that Huion changed it but maybe it is trying to read how fast you spin it. If that doesn't matter to you, you could always check if data[2]  is greater that 0 and data[3] will tell you if you rotated it left.


If I remember correctly keycode 260 is supposed to be the wheel button so you could add the following and it should work:

```
// Convert data to keycodes
if (data[1] != 0)
	keycode = data[1];
else if (data[2] != 0)
	keycode = data[2] + 128;

// Check wheel data
if (wheelData[1] != 0) // Wheel button
	keycode = 260;
else if (wheelData[2] != 0){ // Wheel directions
	keycode = 641;
        if (wheelData[3] != 0)
                  keycode++;
}
```

**Comment by jlitowitz** [comment] 2024-11-08 03:02
Thanks.  I'll keep playing over the next few days.  Your thoughts on the 2 vs 3 value for click vs hold I think may be on the right trail.  I did notice I was getting a whole slew of 3's - I thought maybe I had messed up with my printf lines somehow.

One other thing I noticed, though I don't think it makes a difference.  Your calls to `libusb_interrupt_transfer` pass in NULL instead of a pointer to a length variable.  When I passed in a pointer, I got a value of 8 for all of the 0-17 buttons, but a value of 9 for the wheel and wheel button.  However, I already documented all the differences in the values that I saw, and with data[0] always being 17 for the wheel & button, it seems functionally irrelevant... but who knows.

**Comment by jlitowitz** [comment] 2024-11-08 16:08
[lsusb-v_output.txt](https://github.com/user-attachments/files/17681150/lsusb-v_output.txt)


Ok well I am officially beyond my knowledge & ability here.  I tested the device on a separate Windows machine, and the official software seems to work fine, so it's not a hardware issue.  Attached is the output of `sudo lsusb -v -d 256c:0069` in case it helps you figure out what's going on with the wheel & wheelbutton.

**Comment by mckset** [comment] 2024-11-09 16:25
What you sent just confirms what you found before on how endpoints 0x82 and 0x83 handle the buttons and wheel inputs.

>  Your calls to libusb_interrupt_transfer pass in NULL instead of a pointer to a length variable.

I passed in NULL because the data length is always the for KD100 devices. I gave the data array a size of 40 when testing and forgot to cut that down though it's not that big of an issue. This was my first public C project so there's a lot of areas that could be cleaned up.

As far as your issue goes, I'm not sure exactly what the problem is. I'm guessing that you are still unable to get the wheel to work but I'm not sure which part of it. If you applied my suggestion, I would update the debug section to display the wheel data just to make sure that is working. 

```
if (debug == 2 || dry){
    printf("BUTTON DATA: [%d", data[0]);
    for (int i = 1; i < sizeof(data); i++){
        printf(", %d", data[i]);
    }
    printf("]\n");

    printf("WHEEL DATA: [%d", data[0]);
    for (int i = 1; i < sizeof(wheelData); i++){
        printf(", %d", wheelData[i]);
    }
    printf("]\n");
}
```

If you are getting data from the wheel, then it's just an issue of setting the keycode to match the wheel input. If you run the program with only one "-d" flag, it will display the keycodes for each button that you push so that should tell you what the keycodes for the wheel and wheel button are being read as.

**Comment by jlitowitz** [comment] 2024-11-09 18:30
I ended up having to reformat my machine w/Windows last night, so not going to be able to make any further progress on this at the moment.  I plan on trying to get USB passthrough to WSL work, or worst case, setting up one of my paperweights to try to figure this out.

The real problem at this point isn't keycode conversions.  It's that the calls to `libusb_interrupt_transfer` seem to get data for the last detected motion before getting data for the current motion - even if I stop moving for a few seconds.  You can see that in one of my previous comments.  If I spin it to the left, then immediately to the right, or even if I pause for a few seconds before spinning to the right, the first few data elements retrieved will still look like left-turn signals; after say 6-10 or so, only then will I get right-turn signals.  The same happens if I then whether immediately or after a pause, turn to the left:  I'll continue to get right-turn signals for a bit, and only after 6-10 or so will I get left-turn signals.

I haven't been able to notice a pattern in the wrong-direction signals that could be used to signal, "hey, I'm not actually a left turn signal; I'm actually a right turn signal that just looks like a left one for some strange reason."  I've never done USB coding before.  Are there other calls that could be made to check other bits/statuses of the device?  In looking through the header files, I noticed `libusb_bulk_transfer` and `libusb_control_transfer`, or something like that.  I tried using one of those (I forget which) which had a similar enough parameter list that I could figure out what to send in, but got the same basic results.  The other call was beyond what I could figure out.  Do you think one of those might be worth looking into further?

**Comment by mckset** [comment] 2024-11-09 19:44
I'm not sure if any of those transfer methods would change the results but I could be wrong. If it takes 6-10 turns on the wheel before it reads the right direction I'm wondering if the wheel data is actually showing how much you turned the wheel. If that's the case, maybe you need an integer variable to store the wheels last position and compare it to the received data to see if it increased or decreased. But if you are using Windows now, the Huion drivers should work there without any problem. I'm still surprised they didn't fix their Linux drivers yet
